### PR TITLE
Add translation of 02 strings and regular expressions

### PR DESCRIPTION
**Pull request by victorpavlov**

### CODE REVIEW

**Comment by terrysahaidak** [comment]
@victorpavlov thank you! Now we gonna check it. 
/cc @denysdovhan @Mariannach

**Comment by denysdovhan** [comment]
@terrysahaidak we should check translation before.

**Comment by terrysahaidak** [comment]
@denysdovhan yup, sure :smirk:

**Comment by denysdovhan** [comment]
Я закінчив рев’ю. Виправ. будь–ласка основні помилки якнайшвидше і запуш коміт. Після цього за роботу візьмуться філологи.

**Comment by victorpavlov** [comment]
@denysdovhan Did I understand well, that you finished review, and now I should make changes regarding to all your edits?

**Comment by denysdovhan** [comment]
Yep, fix your mistakes. After that will be another one review.

**Comment by denysdovhan** [comment]
Я відписуюсь від цього реквесту, бо мені приходить занадто багато сповіщень на пошту. Якщо я потрібен, звертайтесь через @denysdovhan.

**Comment by denysdovhan** [comment]
Review has been done. @victorpavlov please fix problems.

**Comment by victorpavlov** [comment]
@denysdovhan I'm on it, will done until Monday.

**Comment by victorpavlov** [comment]
@denysdovhan I did the fixes after first review.

**Comment by denysdovhan** [comment]
Something weird happened. I can't look at diff and your changes do not close related comments.

**Comment by denysdovhan** [comment]
@victorpavlov, I've merged your branch to [`02-strings-and-regexp`](https://github.com/denysdovhan/understandinges6ua/tree/02-strings-and-regexp). I'll fix all others small mistakes and typos.

I don't merge it now, because we have to publish chapter about block bindings before. Thank you for your work! All your commits are still attached to you and I'm gonna mention you when I will merge it.

**Comment by denysdovhan** [comment]
@victorpavlov Join to discussion #3.

**Comment by victorpavlov** [comment]
@denysdovhan Ok, thank you

**Pull request closed without merging**
