### PR TITLE
02 strings and regular expressions chapter translation

### PR DESCRIPTION
**Pull request by victorpavlov**
Translation for “String and Regular expressions”.

# [Diff](https://github.com/denysdovhan/understandinges6ua/compare/b15b9f3...d14336d)

### CODE REVIEW

**Comment by denysdovhan** [comment]
Awesome!

**Comment by denysdovhan** [comment]
We asked to commit untranslated version of chaper. That's because we do compare diff between first and last commit. You haven't done this.

**Comment by denysdovhan** [comment]
And please, squash your commits into two:

* the first commit https://github.com/victorpavlov/understandinges6ua/commit/b15b9f3e928f8f75d3c696ef8e8a766f944b380d
* and other commits from https://github.com/victorpavlov/understandinges6ua/commit/a6b9c91600428f51600cb9a228d3e97062d8b37c to https://github.com/victorpavlov/understandinges6ua/commit/d14336d83b2c1fdfa4aed0b253177a7f203fa04d

**Comment by victorpavlov** [comment]
@denysdovhan  I did the changes. Thank you for reviews. But I thought that in this comment https://github.com/denysdovhan/understandinges6ua/issues/3#issuecomment-173181736 @terrysahaidak  Asked me start add original file ant translate him, without copy of file. Anyway I added original file as you asked.
Thank you.

**Comment by denysdovhan** [comment]
You didn't understand.

We meant you had to do this:

* Copy original file into `manuscript/`. Commit this file.
* Translate this original file and do commits if needed.
* Squash all commits with translations to one.

After that you would have two commits:

1. Commit with file w/o translation.
2. Commit, which containts this file with translation.

Take a look at my https://github.com/denysdovhan/understandinges6ua/pull/16. There are two commits:
image

**Comment by denysdovhan** [comment]
I've gotta close this pr, because commit history is not obvious here. Please send another one.

**Pull request closed without merging**
